### PR TITLE
Fixed #353 - Crash Helditem

### LINKED ISSUE #353: Helditem was being checked even if there was no held item
This causes the server to crash whenever you tried to interact with an object with nothing in the hand

### PR DESCRIPTION
**Pull request by bitknox**
Ref #353

### CODE REVIEW

File: src/lib/plugins/placeBlock.js [hunk 1]
```diff
@@ -15,6 +15,7 @@ module.exports.player = function (player, serv, { version }) {
 
   player._client.on('block_place', ({ direction, location } = {}) => {
     const heldItem = player.inventory.slots[36 + player.heldItemSlot]
+    if(heldItem == undefined) return
```
Comment (rom1504) [inline src/lib/plugins/placeBlock.js]: use ===

File: src/lib/plugins/useItem.js [hunk 2]
```diff
@@ -5,6 +5,7 @@ module.exports.player = function (player, serv, { version }) {
 
   player._client.on('block_place', ({ direction, location } = {}) => {
     const heldItem = player.inventory.slots[36 + player.heldItemSlot]
+    if(heldItem == undefined) return
```
Comment (rom1504) [inline src/lib/plugins/useItem.js]: use ===
and add a space before the ( 
(or run standard --fix to fix these kind of things)
